# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DalePlay\EscuelaTransito\ui_designed\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 652)
        MainWindow.setStyleSheet("QWidget {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.93, y2:0.840909, stop:0 rgba(85, 82, 95, 255), stop:1 rgba(109, 108, 122, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame.setStyleSheet("background-color: rgba(85, 82, 95, 255);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imagen_logo = QtWidgets.QLabel(self.title_frame)
        self.imagen_logo.setText("")
        self.imagen_logo.setPixmap(QtGui.QPixmap("c:\\Users\\DalePlay\\EscuelaTransito\\ui_designed\\VLC.png"))
        self.imagen_logo.setObjectName("imagen_logo")
        self.horizontalLayout.addWidget(self.imagen_logo)
        self.label = QtWidgets.QLabel(self.title_frame)
        self.label.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(776, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.title_frame)
        self.body_frame = QtWidgets.QFrame(self.centralwidget)
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.body_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_frame = QtWidgets.QFrame(self.body_frame)
        self.menu_frame.setMinimumSize(QtCore.QSize(150, 0))
        self.menu_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.horizontalLayout_2.addWidget(self.menu_frame)
        self.tree_frame = QtWidgets.QFrame(self.body_frame)
        self.tree_frame.setMinimumSize(QtCore.QSize(400, 600))
        self.tree_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tree_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tree_frame.setObjectName("tree_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tree_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView = QtWidgets.QTreeView(self.tree_frame)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_2.addWidget(self.tree_frame)
        self.verticalLayout.addWidget(self.body_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Transito Matriculas"))
